config/routes.rb
Rails.application.routes.draw do
  require 'api_constraints'
  root to: 'restraunts#index'
  resources :restraunts
  devise_for :users
  resources :users
  resources :categories
  post 'likes/give', as: 'site_like'
  resources :comments, except: [:create]
  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1,
                                                       default: true) do
      resources :restraunts
      resources :categories
      resources :dishes
      post 'likes/give', as: 'like'
      get 'users/log_in'
      get 'users/log_out'
    end
  end
end

app/models/restraunt.rb
class Restraunt < ActiveRecord::Base
  has_many :categories
  include Likeable
  include Commentable
  validates_presence_of :description, :location, :name
  validates :name, uniqueness: true
end

app/controllers/api/v1/restraunts_controller.rb
class Api::V1::RestrauntsController < ApplicationController
  respond_to :json
  def index
    @restraunts =  Restraunt.includes(categories: [:dishes]).all
    render json: @restraunts
  end
  def show
    @restraunt = Restraunt.find(params[:id])
    render json: @restraunt
  end
end

app/controllers/restraunts_controller.rb
class RestrauntsController < ApplicationController
  before_action :set_restraunt, only: [:show, :edit, :update, :destroy]
# TODO add google map to view
  def index
    @restraunts = Restraunt.includes(:categories, :likes).all
  end

  def show
    authorize @restraunt
    @comment = Comment.new
  end

  def create
    @restraunt = Restraunt.new(restraunt_params)

    respond_to do |format|
      if @restraunt.save
    format.html { redirect_to @restraunt, notice: 'Category was successfully created.' }
    format.json { render action: 'show', status: :created, location: @restraunt }
  else
    format.html { render action: 'new' }
    format.json { render json: @restraunt.errors, status: :unprocessable_entity }
  end
    end
  end

  def update
    respond_to do |format|
      if @restraunt.update(restraunt_params)
        format.html { redirect_to @restraunt, notice: 'Restraunt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restraunt.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restraunt.destroy
     respond_to do |format|
     format.html { redirect_to categories_url }
     format.json { head :no_content }
   end
  end

  def edit
  end

  def new
    @restraunt = Restraunt.new
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restraunt
    @restraunt = Restraunt.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restraunt_params
    params.require(:restraunt).permit(:name, :description, :location)
  end
end

app/helpers/api/v1/restraunts_helper.rb
module Api::V1::RestrauntsHelper
end

app/helpers/restraunts_helper.rb
module RestrauntsHelper
end

app/views/restraunts/_restraunt.html.haml
.col-xs-12.col-sm-6.col-md-6.col-lg-6
  .panel.panel-default.text-center
    %h2= restraunt.name
    - if user_signed_in?
      = link_to site_like_path(restraunt_id: restraunt.id), remote:true, method: :post do
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
      =raw "<span class=\"label label-success label-as-badge\" id=\"restraunt_#{restraunt.id}\">#{restraunt.likes.count}</span>"
    %p= restraunt.description
    - restraunt.categories.each do |category|
      %span= link_to category.name, category, class:"btn btn-sm btn-success "

app/views/restraunts/create.html.haml
%h1 Restraunts#create
%p Find me in app/views/restraunts/create.html.haml

app/views/restraunts/destroy.html.haml
%h1 Restraunts#destroy
%p Find me in app/views/restraunts/destroy.html.haml

app/views/restraunts/index.html.haml
%script{type:"text/javascript", src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyAZpBPg5gw3S3K5VQzO2Olt5behy0Y5Zmo"}
.container
  = render @restraunts

app/views/restraunts/new.html.haml
%h1 Restraunts#new
%p Find me in app/views/restraunts/new.html.haml

app/views/restraunts/show.html.haml
.container
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    .panel.panel-default.text-center
      %h2= @restraunt.name
      - if user_signed_in?
        = link_to site_like_path(restraunt_id: @restraunt.id), remote:true, method: :post do
          <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        =raw "<span class=\"label label-success label-as-badge\" id=\"@restraunt_#{@restraunt.id}\">#{@restraunt.likes.count}</span>"
      %p= @restraunt.description
      - @restraunt.categories.each do |category|
        %span= link_to category.name, category, class:"btn btn-sm btn-success "
      #map-canvas{width: "300px"}= raw"<img src=\"#{@restraunt.location}\">"
      = render "comments/form", comment: @comment, restraunt: @restraunt

app/views/restraunts/update.html.haml
%h1 Restraunts#update
%p Find me in app/views/restraunts/update.html.haml